### ISSUE TITLE
Unnecessary renders

### ISSUE THREAD

**Issue by paddotk** [daniellittledev/react-environment-settings#36]
Hi,
Although this library is very useful, I find it somewhat of an obstacle that you have to render JSX just to execute a function. Moreover, when I put the results in the Redux store, the component renders and loads the settings with each update, which doesn't seem great for performance.

Is there a way to simply import and use the loadSettings() function so that I call this once upon mounting?

**Comment by daniellittledev** [comment]
You should be able to use the `loadSettings<T>(settingsUrl: string)` function in isolation if you import it from `loadSettings.ts`. However, I would not expect the component to render with reach update. It should be the first component in the hierarchy before the any providers. I currently use it in this way without loading the settings more than once.
